# .github/workflows/proxmox.yml
name: Proxmox Container Management

on:
  push:
    branches: ["**"]
  create:
  delete:

jobs:
  manage-container:
    runs-on: self-hosted
    if: github.event_name != 'push' || github.event.created == false
    steps:
      - uses: maxklema/mie-opensource-action@main
        with:
          github_event_name: ${{ github.event_name }}
          github_repository: ${{ github.event.repository.name }}
          github_repository_owner: ${{ github.repository_owner }}
          github_ref_name: ${{ github.event.ref }}
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          proxmox_username: mklema
          container_password: ${{ secrets.CONTAINER_PASSWORD }}
          http_port: 32000
          public_key: ${{ secrets.PUBLIC_KEY }}
          deploy_on_start: y
          require_env_vars: y
          container_env_vars: '{"frontend": { "api_key": "123"}, "backend": { "password": "abc123" }}'
          install_command: '{"frontend": "npm i", "backend": "pip install -r ../requirements.txt"}'
          start_command: '{"frontend": "npm run dev", "backend": "FLASK_ENV=development flask run"}'
          runtime_language: '{"frontend": "nodejs", "backend": "python"}'
          require_services: y
          services: '["mongodb", "docker"]'
          linux_distribution: debian
          multi_component: y
